"""Add config-models

Revision ID: 2988ab38f742
Revises: 1a31ce608336
Create Date: 2025-10-05 14:56:28.124746

"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '2988ab38f742'
down_revision = '1a31ce608336'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leavetype',
    sa.Column('code', sa.String(255), nullable=False),
    sa.Column('name', sa.String(255), nullable=False),
    sa.Column('description', sa.String(255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leavetype_code'), 'leavetype', ['code'], unique=True)
    op.create_table('policy',
    sa.Column('code', sa.String(255), nullable=False),
    sa.Column('name', sa.String(255), nullable=False),
    sa.Column('value', sa.String(255), nullable=False),
    sa.Column('description', sa.String(255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_policy_code'), 'policy', ['code'], unique=True)
    op.create_table('publicholiday',
    sa.Column('date', sa.String(255), nullable=False),
    sa.Column('name', sa.String(255), nullable=False),
    sa.Column('description', sa.String(255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_publicholiday_date'), 'publicholiday', ['date'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_publicholiday_date'), table_name='publicholiday')
    op.drop_table('publicholiday')
    op.drop_index(op.f('ix_policy_code'), table_name='policy')
    op.drop_table('policy')
    op.drop_index(op.f('ix_leavetype_code'), table_name='leavetype')
    op.drop_table('leavetype')
    # ### end Alembic commands ###
